rvm: '2.5.0'

script:
  - bundle exec rake test_setup
  - mkdir -p spec && bundle exec rspec spec
  - bundle exec rake db:create
  - bundle exec rake db:migrate

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq postgresql-server-dev-9.3


before_script:
- psql -c 'create database travis;' -U postgres
