rvm: '2.5.0'

addons:
  code_climate:
    repo_token: 418d3c72e74748a998e609e2dbf9c04b9e7195c4dc412bd1e8e37aad160f47e5

after_success:
  - bundle exec codeclimate-test-reporter
  
script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rspec

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq postgresql-server-dev-9.3


before_script:
- psql -c 'create database travis;' -U postgres
